default_platform(:ios)

platform :ios do
  app_provisioning_profile_identifier = "match AppStore com.tc.esgi.jenkins"

  desc "Lint"
  lane :lint do
    swiftlint(
      output_file: "../build/swiftlint/swiftlint.report.xml",
      config_file: ".swiftlint.yml",
      executable: "Pods/SwiftLint/swiftlint",
      reporter: "checkstyle"
    )
  end

  desc "Test"
  lane :test do
    scan(
      workspace: "esgi.xcworkspace",
      devices: ["iPhone XS"],
      clean: "true",
      code_coverage: "true",
      output_types: "junit",
      output_directory: "../build/scan",
      output_files: 'report.xml',
      slack_only_on_failure: "true"
    )
    slather(
      use_bundle_exec: "true",
    )
  end

  desc "Deploy"
  lane :deploy do
    match(
      type: "appstore",
    )
    disable_automatic_code_signing
    get_provisioning_profile(
      filename: ENV["APP_PROVISIONING_PROFILE_IDENTIFIER"] + ".mobileprovision"
    )
    update_project_provisioning(
      target_filter: "esgi",
      profile: ENV["APP_PROVISIONING_PROFILE_IDENTIFIER"] + ".mobileprovision"
    )
    gym(
      scheme: "esgi",
      include_bitcode: true,
      skip_profile_detection: true,
      clean: true,
      codesigning_identity: ENV["APPSTORE_SIGNING_IDENTITY"],
      verbose: true
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  # error do |lane, exception|
  #   commit = last_git_commit
  #   author = commit[:author]
  #   slack(
  #     message: "WESH " + author + " !!! t'as fait quoi ?",
  #     payload: { "Output" => exception.to_s },
  #     slack_url: "#{ENV['SLACK_HOOK']}",
  #     success: false
  #   )
  # end
end
