# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "esgi")
    upload_to_testflight
  end

  desc "get development certificates using match"
  lane :certificates do
    match(app_identifier: "com.tc.esgi", readonly: true)
  end

  desc "test - danger - swiftlint - slather - slack"
  lane :test do
    swiftlint(
      output_file: "swiftlint.result.json",
      config_file: ".swiftlint.yml",
      executable: "Pods/SwiftLint/swiftlint"
    )
    scan(workspace: "esgi.xcworkspace",
      devices: ["iPhone XS"],
      clean: "true",
      code_coverage: "true",
      output_types: "junit",
      output_directory: "report/scan"
    )
    slather(
      scheme: "esgi",
      workspace: "esgi.xcworkspace",
      html: "true",
      output_directory: "report/slather"
    )
    danger(
      danger_id: "unit-tests",
      dangerfile: "esgi/dangerfile",
      github_api_token: ENV["GITHUB_API_TOKEN"],
      verbose: true
    )
  end

end
